[package]
name = "calendar_bot"
version = "0.1.0"
authors = ["Collin Baker <chbaker0@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
